### ISSUE TITLE
Add screensaver options?

### ISSUE THREAD

**Issue by scottmc** [bbjimmy/Sort-Save#1]
Maybe add options to have it run different sorts of sorts?  Click on the image on this site to see the various sorting algorithms in action.  
http://www.sorting-algorithms.com/
Maybe add more settings for # of colors or other features.

**Comment by bbjimmy** [comment]
sort-save has seven different sorts, two that are not on the list at http://www.sorting-algorithms.com and  missing are selection, merge, and quick3 sorts. it displays the sorts in  seven different display formats, and has many different colors and bar widths. Adding more sorts may be interesting, but settings do not seem to be needed. just my two cents.

**Comment by bbjimmy** [comment]
added more colors, I am open to more sorts, PRs welcome.
